### ISSUE TITLE
Null Reference Exception when copying a mk3 assembler

### ISSUE THREAD

**Issue by patrick-leb** [DysonSphereMod/QOL#1]
That's the only problem i've encountered. Not sure if there is anything I can do to help!

![20210304163218_1](https://user-images.githubusercontent.com/68301566/110033742-c9ded880-7d07-11eb-8f6e-776dc2c8dc52.jpg)

**Comment by brokenmass** [comment]
I think i found the issue (it only happens with very spacing values > stepscount) and the fix should be out soon.

**Comment by brokenmass** [comment]
fixed in 1.0.1
