### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by AchimGrolimund** [DysonSphereMod/QOL#103]
Hey all, did you make an Update for the latest vervion of the Game? Because the actual game ar not running with this mod :-( 

Cheers

**Comment by Chrisalead** [comment]
works fine for me. Except for the "dot" bug still not released. On that matter any chance to have the fixed version release soon ?

**Comment by dyhsu810** [comment]
sometimes there's error message and sometimes not

Thread error exception
idx:9 assembler factroy
idx:0 assembler gametick system.collections.generic.keynotfound exception: the given key was not present in the dictionary

**Comment by AchimGrolimund** [comment]
i try to load it, but it dosn't work. i dont see an Icon ingame and iin the new CLI window i only see this:
![image](https://user-images.githubusercontent.com/22026079/124651414-2eb76480-de9b-11eb-91e7-ef2aa3996980.png)

**Comment by brokenmass** [comment]
fixed in 1.2.1
