### ISSUE TITLE
MultiBuildBeta: Belt-to-Belt Sorters not copied

### ISSUE THREAD

**Issue by themadtinker** [DysonSphereMod/QOL#11]
Sorters that move from items from one belt to another aren't included in blueprints. This sample blueprint should move items from one storage container to another:

H4sIAAAAAAAAC92a227bRhCG34XXErE7s0dfpgfA6EWKtChQFL5QZNoRokiGJKdJA797Z3naFbXLLF0pcJObmFySIvf/duafIb8UH6vdfrXdFFd8Vuyqu2pXbZbVr9t9cfWl+ER7DSslzIrPxZXWJbez4p/iCm3J1dOsWG3c2dWb7rQ320N7GitRaMuUqM9kpaItobA+m5UCudBIV/3bbUkAIVE8Bb//56IeYbNiuX1YVbevHlfr29Xmnu7qry/FLxVdEzjQBf5YrB8r95sPu+1he31L+2lgVmx3q/vVZrGu99RHdnvCR8NSNzeoeYmyeTRZMvnkD/ePNKdnUlxaZupTaFOhkAJMfd7cPZVmxmD/VMKidU+1fNztt7s31XpxWH0MpnYuSt1dije/PlclaDrlw/Zjtf95t/3QT2394J/aSfnc/l9PJnuaRUfmvAQ1GKNfYnx0FEZHcXRUnIzS39wk7teP+btKjUI3yr82fDOcb4/SrlquHipHBHtyl2kxckxHMOLulo4xckfGMIJSygFGgpUmSZEUyrBeeiVAM2t7imiTo+0o4sIyrUcoCieC9xDZ7wiiKEPTdUaTq7M7MqIzxT+s78OIdqYpDipMyoxKaaN6maVWANDLDAwEqj5YKCOFGZdZDIKFJuzOJPOoyqMij2o8KnHuYP/kz5H/pssg15t9tTtQtgozCI9nEMbxZOnTkQ+r5fvfF7v76tAFg1V9Ub/PLds+h3U5y8eO1Wa5/UB7iqu7xXpfzYr9YbE7/LZ21NBUV5vb5u85bTxs9z9W68Oiz6enqpCY7jBIHdcIRMEJXGoNUjNjlICZxWZVyRI5Jeef5qyNQVAaboxUzZ56Wq37x3RzHfCMM6YZlwobylUpLWU9SSeq9h5pEXDmduj6SvPmUvobgnvTCPf67m7vRGKdasGOA6/n3z0Ybd2t1sRJzU+t5g/bx00j0Pbwjgb2r2i+i6vD7rE6SiM8myU+ZEnzCEsmyZIb8iy5GzlCaR6ypEdRgk7xmpExmPqAz45g6hjQvEEA6jjHeYAAKLSoaYcJYNJSRGCqsQTsr2Qk1w07/9R2STBBYA4uRYbsGya7AU5znuCJNTzxiTz18crtPHa7Cb7YCV/A4zZlxMjHE1jg4OfHFn6e9vBv6cbbh03lsqgicQVpPt4ulu+vNw+Ph+bpJN3Quro79LvcrK7u3x3t2D4e+hOQuzndbKrlwRcS3R0O9zeLJjZyvX9dX7QN3kfOIlsaTEqj1VAaQ1k0LY0FxcBLo5DxoBBhqI2XRgijMqVxvlrlivOV5RW/1qmijtdJiip9aUWd48hT1B0ZV9SFjSNFBSdl0opKl3S9W6RpUd4tUh6VbQ51RYFBzW2eolAiDCJZU0c9S9M4HsdDx+VcRG87UW+35C+rN8Rrg1hwTdQGprTD4CpkWdf/ierAau4XMCXNulboOwlWCt7LzSjUZsqtSturwPu6+Ll2a7rckcGT4n3CKI6Oim4UTjBjExkT6tKMuV/IY8wdGWPMlieICfLq6ZDCmVHcM6aYBu0ZU8YIH1KAYpnMY0yWvvViOgnEd4BYJFaZiRzBxXMTxPtVsVgV71cRR1oOQaISYMQIoiET4UECI7jwIDkf6BtWCgFVHkhYChNd6i+CpAgNeiIN/PKZS2fToFM0tCIENGCpbJoGsvq+eymFUCyAQRruE5drbfI8FkTpSw0mfWB/GSxMJcWF8Glxw16aFJ1dpeh4lUIep7WShlPa6QpIk44baK1py/kGFUs5x3dAKQXpoErRYDJNDq9boK0OTUaTTbX0/2iG9vc/XhjpaSYmysNZ69zszIOJNyW8VG2di6XuXpSotIOhCIJBUSSk0AFAaJTyBobstMqMNTT/fQDrYhfd0Et789bf5hgmk43uxTFxv5BpdFkKk9bokr3tMUm/lRXW1K94+2aIkRhQohQGlTOAznQnR5T4Tulz7cnzKcnioFl00zpjF/eqmO1OMO5OXGesfUWvukBKLKTLamFI4qBnSXpD0LMkrwL9SzduETL7YhHT0Cp0dhYyu2bihSUHmd0yk8mWGeihESVF01I7Q+HLW2GlEdJLDVL5FgowwSVO1Pq/t0AzteRTe9pw8Z62WzSZdQUmgzgOe9qSKs+RZG+lDpYuWIu+JQaGa+ndIoV4lekW5+ctMxMt8sFY6puWzPpBTa004eL9K8juX0G8f0VEiGHfAcWo/UNkwedWgqMP5VRZKt1/bIVMSpG5vufnLTUvwMNkXNxKe0nJQGXnfZXI+7yd7wAVVZp0U0Iy96GBR4WSA/PfVIGFunDoPrZxnYlMWM77/uQ5sESc3tQ3Zo6PCzu9xKc0EacX/xjTdSVtI7kJvqLjI30oyv4QvDFjVrDgjRmT9ZegreRcMv58r3dGqzfV6U2t7/DyUmdbA4xbA5Ia25ejllx4JzVLfzFJbk5D2IAGY2VgDYQOrB5IM8HWy0GEbb+F+ZaNpMx2kFs4k1DQF4/zOrvU1/FSn9a6aXuKrO4NNT1Fq0deaikIXD/ZQAwKPCDbCD7Qo5Im3/V7FJqe0BlbQmfpKeZyMs0MNP3eS3By8/QvMa3LBl8wAAA=

**Comment by rampeara** [comment]
Hey, where is this string stored physically?

**Comment by brokenmass** [comment]
it's a know 'issue' or , to be precise, lack of functionality. will be added soon

**Comment by chrisrico** [comment]
> Hey, where is this string stored physically?

The mod can copy the currently selected blueprint to your clipboard, or paste a blueprint from your clipboard.

**Comment by brokenmass** [comment]
fixed in 2.1.0
