### ISSUE TITLE
[Multibuild][Sugesstion] Any chance we can get this functional again, WAY better than the newly implemented version

### ISSUE THREAD

**Issue by barbrady123** [DysonSphereMod/QOL#114]
Title....I miss this mod :(    

Yea, the "official" functionality has a nice screen for organization, but for actual usability, your mod was a million times better.

**Comment by brokenmass** [comment]
thanks for loving my mod, but unfortunately I'm not gonna bring multibuild back to life. 

Let it rest in peace :D
