### ISSUE TITLE
[BetterStats] New patch breaks mod

### ISSUE THREAD

**Issue by heliostellar** [DysonSphereMod/QOL#117]
The new patch released today (0.8.20.7962) broke the mod. The patch adds a new menu for system performance, which is probably why the mod conflicts with it. I am only getting the default stats layout now.

**Comment by altmank** [comment]
I confirm. Also they now hide some items with no production, which may be something undesired by people using the better stats mod.

**Comment by burdoto** [comment]
Working on a fix now.

**Comment by heliostellar** [comment]
Thanks for the quick turnaround!

**Comment by burdoto** [comment]
I would love to open a pull request, but for some reason my Fork seems to be unavailable right now.
The new code for this is actually very simple: ```csharp
        [HarmonyPostfix, HarmonyPatch(typeof(UIProductEntry), "_OnUpdate")]
        public static void UIProductEntry_Update(UIProductEntry __instance)
        {
            if (!displaySec || __instance.productionStatWindow.timeLevel == 5 ||
                !__instance.productionStatWindow.isProductionTab)
            {
                __instance.productUnitLabel.text = __instance.consumeUnitLabel.text = "/min";
                return;
            }
            __instance.productUnitLabel.text = __instance.consumeUnitLabel.text = "/sec";
            var data = __instance.entryData;
            data.consumption /= 60;
            data.production /= 60;
            __instance.ShowInText(__instance.productionStatWindow.timeLevel);
        }
```

**Comment by brokenmass** [comment]
fixed in 1.3.1
