### ISSUE TITLE
error in 0.6.17.5932

### ISSUE THREAD

**Issue by dcheva** [DysonSphereMod/QOL#12]
game version 0.6.17.5932
plugin version brokenmass-MultiBuild-1.1.2
```
Exception hit 4323 times: MissingMethodException: Method not found: 'VFAudio.Create'.
(wrapper dynamic-method) PlayerAction_Build.DMD<PlayerAction_Build..DetermineBuildPreviews> (PlayerAction_Build) <0x00bb9>
MultiBuild.MultiBuild.BuildMainLogic_Prefix (PlayerAction_Build&) <0x0032c>
(wrapper dynamic-method) PlayerAction_Build.DMD<PlayerAction_Build..BuildMainLogic> (PlayerAction_Build) <0x00023>
PlayerAction_Build.GameTick (long) <0x002c0>
PlayerController.GameTick (long) <0x0013f>
Player.GameTick (long) <0x0006c>
(wrapper dynamic-method) GameData.DMD<GameData..GameTick> (GameData,long) <0x00114>
GameMain.FixedUpdate () <0x00262>

Target methods matching by name:
void PlayerAction_Build::DetermineBuildPreviews()
void PlayerAction_Build::BuildMainLogic()
void GameData::GameTick(long time)

Relevant plugins:
...
harmony-auto-d7346aa4-3ffe-4ff8-9e6c-0ff2c0ff8264 - DSP modding pack\Alejandro1-BuildAnywhere-1.4.2\BuildAnywhere.dll
	Postfix[index=1]: static bool BuildAnywhere.PlayerAction_Build_DetermineBuildPreviews_Patch::Prefix(PlayerAction_Build __instance)

==================
```

**Comment by brokenmass** [comment]
weird... it must come from another plugin messing with the audio object.

**Comment by dcheva** [comment]
brokenmass-MultiBuild-1.1.2 working good

**Comment by dcheva** [comment]
my plugins folder is:
`BepInEx\plugins\DSP modding pack
     .
     ..
     alekslt-MineralExhaustionNotifier-0.5.2
     appuns-DSPMultiplyStackSize-1.0.4
     BakaNiner-FILOCraft-1.0.0
     brokenmass-BuildCounter-1.2.0
     brokenmass-MultiBuild-1.1.1
     brotchie-MinerInfo-1.0.1
     dsp-mods-DspGameSpeed-0.7.1
     GreyHak-DSP_Drone_Clearing-1.2.13
     GreyHak-DSP_Save_Game_Sorter-1.0.1
     HarriXS-More_Replication-1.3.1
     KG-Long_Building_Selection_and_Free_M_Globalmap-1.0.0
     KingEnderBrine-SplitterOverConveyor-2.0.1
     kremnev8-AdvancedMiner-1.0.5
     sp00ktober-RenderDistance-0.6.81
     Taki7o7-FreeFoundations_FreeSoil_HigherBuildRange-1.2.4
     Therzok-WhatTheBreak-1.0.2
     thisisbrad-CopyInserters-1.7.0
     Zorb-More_Planet_Types-1.2.0`

**Comment by dcheva** [comment]
> it must come from another plugin messing with the audio object
just copypaste that code into your one :)
