### ISSUE TITLE
2.0.5 MultiBuildBeta Belt Issue

### ISSUE THREAD

**Issue by Delod19** [DysonSphereMod/QOL#15]
When trying to use a Blueprint to connect to a Belt system, the belts do not connect and instead flag as a collision with another "object"

![image](https://user-images.githubusercontent.com/80706733/111189309-5735ee80-858c-11eb-9cfc-004b3798bef1.png)

**Comment by Delod19** [comment]
I also noticed that it doesn't consider elevated belts as well.

**Comment by brokenmass** [comment]
not issue. just lack of functionality.

I might be able to add those in the future but for now please consider those 2 points a limitation of thosm mod.

**Comment by Delod19** [comment]
Okie dokie thank you sir

**Comment by brokenmass** [comment]
belts connection is available in version 2.1.1 and later
