### ISSUE TITLE
don't need foundation support if placed blueprint is on water outside of build range

### ISSUE THREAD

**Issue by lionskull** [DysonSphereMod/QOL#16]
Placing blueprints outside of the build range on water does not require foundation support.
![image](https://user-images.githubusercontent.com/80729330/111242500-87958100-85bc-11eb-93c0-860ee7f1c001.png)
![image](https://user-images.githubusercontent.com/80729330/111242645-d3482a80-85bc-11eb-8227-412d5baa2f03.png)

thank you for the mods

**Comment by brokenmass** [comment]
Thanks, will be fixed soon

**Comment by lionskull** [comment]
You can also place blueprints on other blueprints outside of build range, and place buildings in other buildings. Seems like the same issue.

**Comment by brokenmass** [comment]
fixed in 2.1.0
