### ISSUE TITLE
Blueprints tab blocking flight data when it's open and you go into sail mode.

### ISSUE THREAD

**Issue by EpicPartyGuy** [DysonSphereMod/QOL#17]
![image](https://user-images.githubusercontent.com/80789173/111376263-9ee47500-8675-11eb-85d7-634bea0431c3.png)
Using the MultiBuild mod (ver 2.0.6) when I have the blueprints tab open and go into sail mode it keeps the tab open, blocking the speed and other information. It is replicatable.

**Comment by brokenmass** [comment]
fixed in version 2.1.0 and later
