### ISSUE TITLE
MultiBuild 2.0.6: Copying elevated belts and stacked buildings is broken, it overlaps some and ignores others

### ISSUE THREAD

**Issue by EpicPartyGuy** [DysonSphereMod/QOL#18]
As it says in the title, belts aren't copied correctly if they are not on the ground level.
![image](https://user-images.githubusercontent.com/80789173/111376973-858ff880-8676-11eb-9e1c-d7cddb0ec7a8.png)
On the left was copied, on the right was pasted.

![image](https://user-images.githubusercontent.com/80789173/111377181-ba9c4b00-8676-11eb-8f92-1057564cce2a.png)
Top was copied, bottom was pasted.

**Comment by chrisrico** [comment]
This is a duplicate of #15

**Comment by brokenmass** [comment]
Multilevel belts blueprinting is available in version 2.1.1 and later

**Comment by chrisrico** [comment]
Just want to say that you are a damned rock star!
