### ISSUE TITLE
MultiBuild, possible improvement

### ISSUE THREAD

**Issue by Mr-Cake** [DysonSphereMod/QOL#2]
The adjustable spacing of your mod is excellent addition, i wonder if its possible to remember the spacing for buildings separately? 
So you can put down poles at certain distances and then build the assemblers like normal without having to use +/-.

**Comment by nonoroazoro** [comment]
That's the idea!

**Comment by brokenmass** [comment]
Nice idea. 
Implemented and released in version [1.1.0](https://dsp.thunderstore.io/package/brokenmass/MultiBuild/1.1.0/)
