### ISSUE TITLE
Index out of bounds exception while shift clicking chemical plant with inserters

### ISSUE THREAD

**Issue by lionskull** [DysonSphereMod/QOL#29]
![image](https://user-images.githubusercontent.com/80729330/111714855-d2f39d80-880f-11eb-909f-b92f0b9e4554.png)

**Comment by ham-steamer** [comment]
Received the following index out of bounds error when attempting to add conveyors to an interplanetary logistics hub.
![dsp_err](https://user-images.githubusercontent.com/35670434/111809057-f881b500-88aa-11eb-886e-1fd7b3baa14e.png)

**Comment by brokenmass** [comment]
@ham-steamer : 1 ) you should add the version of the mod you are using . 2) it might have already been fixed in 2.1.3

**Comment by ham-steamer** [comment]
It was 2.1.3. I downloaded this ~1 hour ago and almost immediately started receiving this error.

**Comment by brokenmass** [comment]
@ham-steamer please check 2.1.4

**Comment by Cryptically** [comment]
I'm on v2.1.4

Randomly having the same issues, with smelters and assemblers too.

**Comment by brokenmass** [comment]
should be fixed in 2.2.0
