### ISSUE TITLE
Thanks for your mods + an idea

### ISSUE THREAD

**Issue by kyldvs** [DysonSphereMod/QOL#3]
Thanks for all your mods, they are huge QOL improvements!

If you are accepting requests one mod that I would love to see is something that would help find bottlenecks and spit out production capacity/consumption for the current planet. I'm thinking it would work like:

- click button to start mod -->
- look at all the smelters/assemblers/etc on the current planet -->
- calculate theoretical maximum production/consumption assuming they work at 100% -->
- spit it out in some format, either in the UI or a file like [Resource Spreadsheet Generator](https://dsp.thunderstore.io/package/GreyHak/DSP_Star_Sector_Resource_Spreadsheet_Generator/) does

**Comment by brokenmass** [comment]
looks like a nice idea.

**Comment by alekslt** [comment]
This also ties into a discussion I had with another person, where you could designate areas of the planet and have statistics per area. 
When I get time to work on DSP-stuff again and after moving my current mod UI into the normal Unity UI (inside the stats-window) that's probably something I want to explore as well, unless @brokenmass does it first :) Ideally we could offload all mods onhim

**Comment by brokenmass** [comment]
@kyldvs contact me on discord please

**Comment by brokenmass** [comment]
@kyldvs this is now reality : https://dsp.thunderstore.io/package/brokenmass/BetterStats

**Comment by kyldvs** [comment]
Amazing work as always!
