### ISSUE TITLE
Sorters cannot be placed on belts that are connecting to existing ones

### ISSUE THREAD

**Issue by randomlypickedname** [DysonSphereMod/QOL#32]
Not a major issue at all, but would it be possible to allow that? Just for example:
![image](https://user-images.githubusercontent.com/37277745/111789165-1684f080-887e-11eb-965b-be7ce7fe0504.png)

**Comment by randomlypickedname** [comment]
Actually, it appears input sorters can't be placed on belts at all:
![image](https://user-images.githubusercontent.com/37277745/111790014-01f52800-887f-11eb-8f44-0c371d3c4e1d.png)

**Comment by DiamaiD** [comment]
I get the same problem. It accures with fresh started game after you place a line of buildings with the alt-key. After that inserters cant be placed anymore.

**Comment by brokenmass** [comment]
@DiamaiD can you check 2.1.2 please ?

**Comment by DiamaiD** [comment]
@brokenmass on version 2.1.3 everything works fine, thanks for the quick fix!
