### ISSUE TITLE
CopySorters function is broken

### ISSUE THREAD

**Issue by RubenBroere** [DysonSphereMod/QOL#34]
Can't copy building with sorters. It says the sorters are obstructed on a belt. Worked fine previously.
![Bug](https://user-images.githubusercontent.com/44034895/111808246-1f081600-88d4-11eb-93e7-81bc5271a704.png)

**Comment by ham-steamer** [comment]
I have the same issue.

**Comment by brokenmass** [comment]
@RubenBroere  / @ham-steamer  can you test the latest version 2.1.3 ?

**Comment by RubenBroere** [comment]
Sorry i hadn't seen the newest version and all is fixed.
