### ISSUE TITLE
game error with liquid storage tanks

### ISSUE THREAD

**Issue by DiamaiD** [DysonSphereMod/QOL#35]
On version 2.1.0 and 2.1.3, as soon as I hover with a belt over a second level of liquid storage tanks my game freezes as long as I stay with the mouse over it and I get this error:
![jeP5BgK95q](https://user-images.githubusercontent.com/44055520/111811452-56c48d00-88d7-11eb-87ce-ade7d9252bce.jpg)

**Comment by brokenmass** [comment]
@DiamaiD fixed in 2.1.4
