### ISSUE TITLE
[MultiBuildBeta] IndexOutOfRangeException when coping building with unfinished inserter

### ISSUE THREAD

**Issue by Al-bchen** [DysonSphereMod/QOL#36]
Ver 2.1.4, using r2modman

When I start to copy buildings that has inserters to be built (but not done), this exception raises immediately.

**Comment by Al-bchen** [comment]
![20210319184837_1](https://user-images.githubusercontent.com/43048473/111850452-bbd3af00-88e6-11eb-88d7-dcc4069c3c66.jpg)

**Comment by Al-bchen** [comment]
![20210319185956_1](https://user-images.githubusercontent.com/43048473/111850467-c55d1700-88e6-11eb-8f4d-2b0002c0e74a.jpg)

**Comment by tjvezina** [comment]
I encountered the same thing just now, but didn't notice the inserter hadn't been placed yet - good catch

![20210319204340_1](https://user-images.githubusercontent.com/1713664/111854312-e9bff000-88f4-11eb-8406-3ea06685155d.jpg)

**Comment by RubenBroere** [comment]
Same for me I think. I saw the error but did not see the unfinished sorter.
![Bug2](https://user-images.githubusercontent.com/44034895/111870593-f04a7800-8985-11eb-8c22-ccbca40980aa.png)

**Comment by RJWoodhead** [comment]
Also just ran into this; unfinished sorter explanation is also likely in my case.

**Comment by brokenmass** [comment]
should be fixed in 2.2.0
