### ISSUE TITLE
ArgumentOutOfRangeException 

### ISSUE THREAD

**Issue by Cryptically** [DysonSphereMod/QOL#39]
![image](https://user-images.githubusercontent.com/8995942/111871141-a1233800-89c3-11eb-8b97-5d2071adc58c.png)

Mod v2.1.4, game v 0.6.17.5972
1. use blue print
2. copied 3 conveyer belts 
3. right click (go to to build mode)
4. press alt 
5. get error

**Comment by brokenmass** [comment]
should be fixed in 2.2.0
