### ISSUE TITLE
Filters/Priorities on splitters not copied with blueprint.

### ISSUE THREAD

**Issue by supremacy2k** [DysonSphereMod/QOL#40]
Hi.

When copying splitters, the filters and/or priorities are not copied, so when building a blueprint you'd have to figure out how the splitters are set up.

This can be an issue with other peoples blueprints.

Otherwise, love the mod! :)

**Comment by RJWoodhead** [comment]
Confirming this issue.

**Comment by supremacy2k** [comment]
I noticed it on this blueprint.

Don't know if it's an issue, or if creator of blueprint didn't set them.

**Comment by StarrrLiteNL** [comment]
I can confirm it is an issue with the mod not copying them.
When I set priorities and then copy the splitter, the copied splitters have no priorities and/or filters set anymore

**Comment by brokenmass** [comment]
fixed in multibuildbeta 2.3.0
