### ISSUE TITLE
Idea - Icarus Logistic Station + Improvement

### ISSUE THREAD

**Issue by callmephil** [DysonSphereMod/QOL#45]
Add 1 **interstellar slot command to Icarus's internal inventory**. 
`Use Mecha Energy, Wrapper & drone for request and delivery.`

**Improve logistic station min/max configuration by adding an additional filter for each supplied/requested/stored item.**
```
Use case example with Hydrogen: 
1. Request 2500 locally
2. Request 2500 From Orbital Collector
3. Store 5000 From Belt 
3. Supply 7500 Locally 
4. Supply 2500 Remotely 
```

**Specific LS Target List Selection.**
```
Use case example:
1. ILS A Request from solar system X and Supply to Solar System Y Station B
2. ILS Request Deuterium from station A B C & D Supply To E & F
```

**ILS Statistics Panel Tab**
```
1. Track Supply & Demand of ILS(s) for solar systems & planets
2. Track available quantity per station/item.
```

I'm fine in C# however my knowledge in modding unity games is close to none but I'm available to support in developing this or bug fixes & testing.

Let me know what you think! Also big thanks for your mods they're a life changer!

**Comment by brokenmass** [comment]
This functionality would require to store data in the savegame and so could break a save after an update.
I'm sticking to a policy of only developing mods that do not compromise the savegame. This is mostly for my peace of mind as I don't want unhappy 'users' to start complaining that the mod ruined hundreds of hours of effort.

Said so it's a great idea: this together with the ability to priritise certain logistic station should definetely be integrated into vanilla, so please add this idea to the 'idea' channel in the official dsp discord if you haven't already.
