### ISSUE TITLE
[MultiBuild] [Bug] Dismantle mode deselects blueprint

### ISSUE THREAD

**Issue by delreich** [DysonSphereMod/QOL#49]
If you enter "Dismantle Mode" while holding a blueprint, when you exit back to "Building Mode" you're only holding a basic building.

Steps to reproduce:
- shift-click building with sorters attached or select a blueprint
- press `x`
- press `x`

Expected results:
- Same thing held.

Actual results:
- Bare building held.

MultiBuild v2.2.0, BepInEx5.4.5, as installed by r2modman 3.1.9.

**Comment by delreich** [comment]
The rotation things seems to be a separate bug, and probably happens on shift-click rather than on anything to do with dismantling. New issue incoming.

**Comment by brokenmass** [comment]
for now this is a `wontfix`. I might consider revising this behaviour in the future.

**Comment by delreich** [comment]
> I might consider revising this behaviour in the future.

Please do. The current behaviour makes it quite a bit more difficult to move a building a tile or two along a set of belt, or turn it the other way around.
