### ISSUE TITLE
MultiBuild broken after update

### ISSUE THREAD

**Issue by ezonius** [DysonSphereMod/QOL#5]
![image](https://user-images.githubusercontent.com/61872098/110946300-ffef0e80-833e-11eb-8430-3e93753d1c80.png)

Happens when I try to copy a Smelter or Assembling Machine.

**Comment by mkaito** [comment]
That's CopyInserters, not MultiBuild.

**Comment by ezonius** [comment]
> That's CopyInserters, not MultiBuild.

Was just about to write that it might be a problem with CopyInserters. Noticed after reading the error message again.

**Comment by mkaito** [comment]
https://github.com/fezhub/DSP-Mods/issues/36

Add your picture here for reference.
