### ISSUE TITLE
[MultiBuild] Method not found error

### ISSUE THREAD

**Issue by CloseProximity4** [DysonSphereMod/QOL#55]
Received error after update when trying to copy multiple items (F1) (F2). (See Screenshot)

NOT YOUR ISSUE. Sorry.

![20210401063359_1](https://user-images.githubusercontent.com/81758530/113299596-47234c00-92ba-11eb-9d4e-b4b69906ee29.jpg)

**Comment by brokenmass** [comment]
The issue was in the version 2.0.2 of `SplitterOverConveyor` and has been fixed in version 2.0.3
