### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by MartinPolygonflow** [DysonSphereMod/QOL#56]
I'm getting these exceptions all the time since last update.
Methods it complains about:
PlanetTransport class, SetStationStorage() method
Disabling the mod and BepInEx gets rid of the error

Full error:
MissingMethodException: Method not found: 'PlanetTransport.SetStationStorage'
(wrapper dynamic-method) PlayerAction_Build.DMD<PlayerAction_Build..NotifyBuilt> (PlayerAction_Build,int,int)
PlaetFactory.BuildFinally (Player,int)
MechaDroneLogic.Build (int)
MechaDroneLogic.UpdateDrones (single)
MechaDroneLogic.GameTick (long,single)
Mecha.GameTick (long,single)
Player.GameTick (long)
GameData.GameTick (long)
GameMain.FixedUpdate ()

**Comment by RJWoodhead** [comment]
Confirmed. It occurred when I built an ILS, and I also got about 15 error messages a second about not enough drones in inventory (when in fact there were).

**Comment by brokenmass** [comment]
It was fixed yesterday, immediatly after (30 min) the release of the new patch, in version `2.2.1`. 

Please ensure you are running the latest version (restart modman or do a manula refresh) before raising an issue..

**Comment by RJWoodhead** [comment]
@brokenmass Actually, I was running the latest version (I check before all play sessions). The problem was actually with AutoStationConfig, but I was mislead because it happened during a Blueprint deploy.

**Comment by MartinPolygonflow** [comment]
Thank you - issue is resolved.
