### ISSUE TITLE
[Multibuild] [Bug] Game error when entering the sphere editor

### ISSUE THREAD

**Issue by kris44dad** [DysonSphereMod/QOL#59]
With the newest version of Multibuild I get a game error (red message box) that is 100% reproducible for me.  I warp to a star system, and when I enter the sphere editor the error occurs.  I did disable Copy Inserters. It doesn't occur in vanilla. I don't know if it's your mod, or an incompatibility with another.
![Screenshot 2021-04-02 18 44 42](https://user-images.githubusercontent.com/38141726/113462135-155ad400-93e5-11eb-8943-5b73f7e369f2.png)
If you are interested in investigating this, I can provide a save game file, as well as the mods (and their versions) I am using. Let me know...

**Comment by brokenmass** [comment]
it's not caused by my mod. `SphereProgress` by thisisbrad is not compatible with the latest version of the game.

**Comment by kris44dad** [comment]
Think you for the information. I'll disable that.
    On Saturday, April 3, 2021, 03:22:37 PM CDT, Marco Massarotto ***@***.***> wrote:  
 
 


it's not caused by my mod. SphereProgress by thisisbrad is not compatible with the latest version of the game.
