### ISSUE TITLE
Unable to compile BetterStats

### ISSUE THREAD

**Issue by zhangxp1998** [DysonSphereMod/QOL#61]
Getting error:
"UIProductionStatWindow' does not contain a definition for 'entryPool' and no accessible extension method 'entryPool' accepting a first argument of type 'UIProductionStatWindow' could be found (are you missing a using directive or an assembly reference?)"

Even though I already added Assembly-CSharp, UnityEngine.dll and many other files from game folder.

**Comment by brokenmass** [comment]
you have to use Assembly-CSharp refstub with all private methods/properties made public. you can find the latest version in the resource channel of dsp modding discord or you can create it yourself using [Stubber-Publicizer](https://github.com/Reinms/Stubber-Publicizer) (download the executable drag and drop assembly-csharp.dll on `ConsoleStubber.exe` and follow the onscreen instructions
