### ISSUE TITLE
[MultiBuildBeta] 2.3.2 shift click matrix lab causes Argumentoutofrange

### ISSUE THREAD

**Issue by fauowlsgeek** [DysonSphereMod/QOL#68]
game version 0.6.17.6137
![2021-04-08 (2)](https://user-images.githubusercontent.com/82191958/114120703-011e4780-98bb-11eb-9f86-092b1867b513.png)

**Comment by brokenmass** [comment]
nice bug ! interesting fact is that the issue was present in every version > 2.1.1 but was not raising an error.

**Comment by brokenmass** [comment]
@fauowlsgeek  fixed in 2.3.3

**Comment by fauowlsgeek** [comment]
awesome work, thanks!
