### ISSUE TITLE
[MultibuildBeta] moving fast with huge blueprints make game crash

### ISSUE THREAD

**Issue by aria1th** [DysonSphereMod/QOL#70]
it happened after 2.3.2 update (I guess) **from yesterday.** game does not causes error messages and just crashes when some problem happens. I guess it has some problems with chaining belts or collision boxes... 

no other mods are being used. 2.3.5 update made it somehow more stable, but it still happens randomly. 

 H4sIAAAAAAAAC+19W48dR3Lmf+Eze5GV99SjbRgQsFgvLL8sFvNAUy25YYotkK1ZLwbz312VWZLIzohgfXl4Oord+TDA6BxWn4pLZty+iPjbq7/efvh4d//+

just hold this blueprint at any planet, and move around up and down... and eventually game will just crash.

**Comment by brokenmass** [comment]
@aria1th  can you send me a ling from https://www.dysonsphereblueprints.com/ with a bp that consistently crash your game ?

**Comment by aria1th** [comment]
its not actually single one : seems like every blueprints can cause crash, even without ILS too... 
https://www.dysonsphereblueprints.com/blueprints/crystal-silicon-480-s-25830-min-assembler-version-equatorial-insanity-build
I just got crash with this one too, and also https://www.dysonsphereblueprints.com/blueprints/large-equator-power-belt-solar-wind this one too. small ones can cause crash too but it takes long time... maybe some memory leak?

**Comment by brokenmass** [comment]
not sure if memory leak or multithreading collision. i'm investigating

**Comment by aria1th** [comment]
was it enough to reproduce?

**Comment by brokenmass** [comment]
@aria1th yes and i solved it ! thanks!

**Comment by brokenmass** [comment]
Fixed in MultibuildBeta 2.3.6
