### ISSUE TITLE
[enhancement] will stacked building blueprint export be added?

### ISSUE THREAD

**Issue by aria1th** [DysonSphereMod/QOL#71]
especially research facilities are not currently being copied / exported, and clicking it thousands of times makes my hand very tired.
if it is nearly impossible or not feasible due to existing export code structure, or vanilla limit, can fastclicking / auto stacking be added?

**Comment by brokenmass** [comment]
@aria1th  yes the ability to copy paste stacked building will be added soon

**Comment by brokenmass** [comment]
actually soon means "right now" :D

**Comment by brokenmass** [comment]
added in multibuildbeta 2.3.7
