### ISSUE TITLE
Feature Request: Mass Recipe/Filter Paste

### ISSUE THREAD

**Issue by RJWoodhead** [DysonSphereMod/QOL#72]
It would be ridiculously useful if you could copy an assembler recipe (<), select a bunch of buildings in blueprint mode, and then hit a key to paste the recipe into all the selected buildings that can accept it. Ditto with filters. Probably needs to have different keys for each paste type for finer control.

**Comment by brokenmass** [comment]
you can use a separate mod for that : https://dsp.thunderstore.io/package/wingless/RecipePasteBrush/
