### ISSUE TITLE
[BetterStats] Deuterium Fractionators listed as consumers of Deuterium

### ISSUE THREAD

**Issue by phoenixx-666** [DysonSphereMod/QOL#74]
My stats panel lists 0 producers of Deuterium while the number of consumers are about the total number of Deuterium Fractionators + actual Deuterium consumers.

**Comment by brokenmass** [comment]
oh yes, you are right  ! thanks for the report!

**Comment by brokenmass** [comment]
fixed in betterstats 1.1.2
