### ISSUE TITLE
MultiDestruct depreciated on Thunderstore?

### ISSUE THREAD

**Issue by 5thHorseman** [DysonSphereMod/QOL#8]
Reference: https://dsp.thunderstore.io/package/brokenmass/MultiDestruct/

Sorry if this isn't the place for requests like this, I couldn't find another.

MultiDestruct is not listed on Thunderstore anymore, and says on its page (luckily for me I had a direct link saved) that it "has been marked as deprecated, and it's suggested another alternative is used."

I see no such alternative. I thought maybe the new Blueprinting mod would have the functionality but it doesn't seem to.

Is this depreciation incorrect, or is there an alternative I don't know about. If so, what is that alternative? I would suggest putting a link to that alternative in the Thunderstore page. It would have saved my confusion.

**Comment by 3therios** [comment]
There's two versions of the mod out now. The [MutliBuildBeta](https://dsp.thunderstore.io/package/brokenmass/MultiBuildBeta/) and the [MultiBuild](https://dsp.thunderstore.io/package/brokenmass/MultiBuild/).

The `beta` version adds blueprint functionality but does additionally clash with the CopyInserters mod.

**Comment by 5thHorseman** [comment]
Sorry again, I'm not a frequent Github user and thought I was posting on MultiDestruct only.

I was not aware of a dev update that makes MultiDestruct useless. I'll poke around and see what I find.

**Comment by kyldvs** [comment]
The developers of DSP added the functionality of MultiDestruct to the core game in their latest update: https://store.steampowered.com/news/app/1366540/view/4178750236020840924

"The Mass Upgrade / Dismantle function is now available!"

**Comment by 5thHorseman** [comment]
Thank you! I have no idea how I missed that.

**Comment by kyldvs** [comment]
No worries, I missed it too when first trying to figure out why the mod was deprecated :)
