### ISSUE TITLE
[BUG] BetterFPS Crash in Planetary Transport system

### ISSUE THREAD

**Issue by ecielam** [DysonSphereMod/QOL#83]
Stack Trace:

========== OUTPUTTING STACK TRACE ==================

0x00007FFDD5516B6C (UnityPlayer) UnityMain
0x00007FFDD561FD9F (UnityPlayer) UnityMain
0x0000025C0C077E2C (Mono JIT Code) (wrapper managed-to-native) UnityEngine.ComputeBuffer:DestroyBuffer (UnityEngine.ComputeBuffer)
0x0000025C0C077D3C (Mono JIT Code) UnityEngine.ComputeBuffer:Dispose (bool)
0x0000025C0C077CC2 (Mono JIT Code) UnityEngine.ComputeBuffer:Dispose ()
0x0000025C0C077C6D (Mono JIT Code) UnityEngine.ComputeBuffer:Release ()
0x0000025CC3E474B8 (Mono JIT Code) CargoContainer:Expand2x ()
0x0000025C0C10D277 (Mono JIT Code) CargoContainer:AddCargo (int)
0x0000025D0441AF04 (Mono JIT Code) CargoPath:TryInsertItemAtHead (int)
0x0000025D04447802 (Mono JIT Code) StationComponent:UpdateIOSlots (CargoTraffic,SignData[])
0x0000025C0C0FCE30 (Mono JIT Code) PlanetTransport:GameTick (long,bool)
0x0000025C0C0F1AEA (Mono JIT Code) PlanetFactory:GameTick (long)
0x0000025C0C0F004C (Mono JIT Code) BetterFPS.BetterFPS/<>c__DisplayClass6_1:<GameData_GameTick_Patch>b__1 ()
0x0000025C0C0EFB7B (Mono JIT Code) System.Threading.Tasks.Task:InnerInvoke ()
0x0000025C0C0EF68C (Mono JIT Code) System.Threading.Tasks.Task:Execute ()
0x0000025C0C0EF33B (Mono JIT Code) System.Threading.Tasks.Task:ExecutionContextCallback (object)
0x0000025C0C0ED6D2 (Mono JIT Code) System.Security.SecurityContext:Run (System.Security.SecurityContext,System.Threading.ContextCallback,object)
0x0000025C0C0ECD86 (Mono JIT Code) System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
0x0000025C0C0EC6DF (Mono JIT Code) System.Threading.Tasks.Task:ExecuteWithThreadLocal (System.Threading.Tasks.Task&)
0x0000025C0C0EB369 (Mono JIT Code) System.Threading.Tasks.Task:ExecuteEntry (bool)
0x0000025C0C0EB188 (Mono JIT Code) System.Threading.Tasks.ThreadPoolTaskScheduler:TaskExecuteWaitCallback (object)
0x0000025C60C70136 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this___object (object,intptr,intptr,intptr)
0x00007FFDD48B6783 (mono) mono_set_defaults
0x00007FFDD4808AD9 (mono) mono_runtime_invoke
0x00007FFDD480EFEF (mono) mono_runtime_invoke_array
0x00007FFDD480F2C4 (mono) mono_runtime_invoke_array
0x00007FFDD482F95B (mono) mono_security_set_mode
0x00007FFDD48303B2 (mono) mono_security_set_mode
0x00007FFDD48340FF (mono) mono_thread_interruption_request_flag
0x00007FFDD48EA1AB (mono) mono_unity_gc_is_disabled
0x00007FFE62937034 (KERNEL32) BaseThreadInitThunk
0x00007FFE647E2651 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

**Comment by brokenmass** [comment]
solved in betterFPS 1.0.3
