### ISSUE TITLE
[BetterFPS] inventories don't update 

### ISSUE THREAD

**Issue by haragei** [DysonSphereMod/QOL#84]
With latest patch release, the inventories don't update the items and stacksizes anymore. 
Only when closing & opening the chest/inventory newly it does update contents one single time.

**Comment by Tuhwin** [comment]
Same here. Worked fine in 1.0.2.
I use the mod that modifies stack sizes, if that matters.
https://dsp.thunderstore.io/package/appuns/DSPMultiplyStackSize/

**Comment by GlitchHound** [comment]
Also experiencing this, no mods affecting inventory (and neither of those listed here), except maybe StackSplitPro. https://dsp.thunderstore.io/package/Bixbite/StackSplitPro/

**Comment by Tuhwin** [comment]
1.0.4 fixed it for me!

**Comment by brokenmass** [comment]
@GlitchHound / @haragei  can you please confirm ?

**Comment by haragei** [comment]
@brokenmass jopp, all's fixed now. thanks a bunch for the blazing fast fix
