### ISSUE TITLE
[BetterFPS] Error Accessing 32800 bytes at offset 0 for Compute Buffer of size 32768 bytes is not possible

### ISSUE THREAD

**Issue by GlitchHound** [DysonSphereMod/QOL#85]
This is occurring on a save when building on a planet it in a new system (first planet in the system which is being modified). No dyson sphere. Config is set to only suppress sphere mesh, no parallelization. I have confirmed that the error does not occur when BetterFPS is disabled.

Full error transcribed:
ArgumentException: ComputeBuffer.SetData(): Accessing 32800 bytes at offset 0 for Compute Buffer of size 32768 bytes is not possible.
UnityEngin.ComputeBuffer.SetData (System.Array data, Int32 managedBufferStartIndex, Int32 computeBufferStartIndex, Int32 count)
CargoContainer.Draw (UnityEngin.Camera.cam)
FactoryModel.DrawInstancedBatches (UnityEngine.Camera cam)
FactoryModel.LateUpdate ()

I haven't quite narrowed down the exact conditions that trigger the problem, but I have a save where I was building a row of 60 refineries, with three belts in front of them (one input, two outputs), with filtered sorters. I had 20 of them in line and blueprinted with belts configured so everything would connect. The error happens anytime between the 21st and 60th refiner, and at the time that it occurs it causes all factory models to disappear (planet mesh remains, but buildings and plants and assorted doodads are gone).

I've had occasions where I successfully built refiners 21-40 and others where it breaks in the process of building those.

I've tried just idling for a bit to make sure it's not some background process. If I wait several minutes (far longer than it takes the error to occur than when I actively continue building), nothing happens, but it will break when I continue.

I thought that the error might be due to product stacking or something (since the stack shows CargoContainer and I have no chests/tanks here), but cannot replicate without creating more than 20 refineries. Also checked the ILS on the planet but there's nothing suspicious there.

I'm backing up the autosave that has the first 20 refineries set up, let me know if you want it.

Config:
hideDysonSphereMesh: true
parallelFactories: false
disableShadows: false

Dependency String list (again, error does not occur if I disable BetterFPS but leave the others enabled):
xiaoye97-BepInEx-5.4.5
alekslt-MineralExhaustionNotifier-0.5.2
sp00ktober-RenderDistance-0.7.0
brotchie-MinerInfo-1.0.1
doobist-Toggle_God_Mode-1.0.1
Windows10CE-IcarusColorPicker-1.1.0
Touhma-Touhma_GalacticScale-1.0.1
HarriXS-No_Advisor-1.2.0
brokenmass-RailgunsRetargeting-1.3.1
brokenmass-BuildCounter-1.2.0
brokenmass-BetterStats-1.2.0
Bixbite-StackSplitPro-1.0.0
Fuhduki-DestructorModeReset-1.1.0
ctcDNightmare-NoPrologue-1.0.0
thisisbrad-SphereProgress-1.1.0
brokenmass-BetterFPS-1.0.3
brokenmass-MultiBuild-2.3.8

**Comment by brokenmass** [comment]
fixed in betterFPS 1.0.4, thanks for reporting the issue
