### ISSUE TITLE
[BetterFPS] [1.0.4] Game constantly crashing

### ISSUE THREAD

**Issue by Veretragna** [DysonSphereMod/QOL#86]
I track this mod from release date and it crashes my game all the time.
It always happens once I load the game. If I don't move mecha, everything runs smoothly (more or less), but when I move, game crashes. It crashes even if I don't move, but it takes some more time. Seems like it's not related with my actions. 
I started a new game, just tomorrow did few flights to nearest solar system and my factory clearly isn't "mega". 
If I can provide more info to track this issue (logs etc.), please point what I can do.

**Comment by brokenmass** [comment]
can you provide the error stack trace ?

**Comment by brokenmass** [comment]
can you also test fbetterFPS 1.0.5  ?

**Comment by Veretragna** [comment]
Just installed 1.05, and so far it's running well. No crashes at all. Thanks!
Problem solved.
