### ISSUE TITLE
[BetterFPS 1.0.4] Crash while constructing more railguns

### ISSUE THREAD

**Issue by Simon-Gau** [DysonSphereMod/QOL#87]
I crashed while adding railguns to my currently-building-a-Dyson-Sphere planet.

Heres the stack trace.

0x00007FF923956B6C (UnityPlayer) UnityMain
0x00007FF923A5FD9F (UnityPlayer) UnityMain
0x000001AF4756D76C (Mono JIT Code) (wrapper managed-to-native) UnityEngine.ComputeBuffer:DestroyBuffer (UnityEngine.ComputeBuffer)
0x000001AF4756D67C (Mono JIT Code) UnityEngine.ComputeBuffer:Dispose (bool)
0x000001AF4756D602 (Mono JIT Code) UnityEngine.ComputeBuffer:Dispose ()
0x000001AF4756D5AD (Mono JIT Code) UnityEngine.ComputeBuffer:Release ()
0x000001AF4757B27B (Mono JIT Code) DysonSwarm:SetBulletCapacity (int)
0x000001B018E81DEB (Mono JIT Code) DysonSwarm:AddBullet (SailBullet,int)
0x000001AF2CBF9888 (Mono JIT Code) (wrapper dynamic-method) EjectorComponent:DMD<EjectorComponent::InternalUpdate> (EjectorComponent&,single,DysonSwarm,AstroPose[],AnimData[],int[])
0x000001AF2CBF1D13 (Mono JIT Code) (wrapper dynamic-method) com.brokenmass.plugin.DSP.BetterFPS.BetterFPS:DMD<com.brokenmass.plugin.DSP.BetterFPS.BetterFPS::DysonSphereRelatedGameTick> (FactorySystem)
0x000001B018E6B675 (Mono JIT Code) com.brokenmass.plugin.DSP.BetterFPS.BetterFPS/<>c:<FactorySystem_DrawModels_Patch>b__8_0 (FactorySystem)
0x000001AF2CBF377A (Mono JIT Code) (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:<FactorySystem_DrawModels_Patch>b__8_0 (FactorySystem)
0x000001AF24A6DC3E (Mono JIT Code) (wrapper dynamic-method) FactorySystem:DMD<FactorySystem::GameTick> (FactorySystem,long,bool)
0x000001AF472B3A06 (Mono JIT Code) (wrapper dynamic-method) PlanetFactory:DMD<PlanetFactory::GameTick> (PlanetFactory,long)
0x000001B018E5E72C (Mono JIT Code) com.brokenmass.plugin.DSP.BetterFPS.BetterFPS/<>c__DisplayClass6_1:<GameData_GameTick_Patch>b__1 ()
0x000001B018E5DFAB (Mono JIT Code) System.Threading.Tasks.Task:InnerInvoke ()
0x000001B018E5D26C (Mono JIT Code) System.Threading.Tasks.Task:Execute ()
0x000001B018E5CC5B (Mono JIT Code) System.Threading.Tasks.Task:ExecutionContextCallback (object)
0x000001B018E58DE2 (Mono JIT Code) System.Security.SecurityContext:Run (System.Security.SecurityContext,System.Threading.ContextCallback,object)
0x000001B018E57836 (Mono JIT Code) System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
0x000001B018E5712F (Mono JIT Code) System.Threading.Tasks.Task:ExecuteWithThreadLocal (System.Threading.Tasks.Task&)
0x000001B018E565C9 (Mono JIT Code) System.Threading.Tasks.Task:ExecuteEntry (bool)
0x000001B018E563C8 (Mono JIT Code) System.Threading.Tasks.ThreadPoolTaskScheduler:TaskExecuteWaitCallback (object)
0x000001AF176C0136 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this___object (object,intptr,intptr,intptr)
0x00007FF95B536783 (mono) mono_set_defaults
0x00007FF95B488AD9 (mono) mono_runtime_invoke
0x00007FF95B48EFEF (mono) mono_runtime_invoke_array
0x00007FF95B48F2C4 (mono) mono_runtime_invoke_array
0x00007FF95B4AF95B (mono) mono_security_set_mode
0x00007FF95B4B03B2 (mono) mono_security_set_mode
0x00007FF95B4B40FF (mono) mono_thread_interruption_request_flag
0x00007FF95B56A1AB (mono) mono_unity_gc_is_disabled
0x00007FF9CB817034 (KERNEL32) BaseThreadInitThunk
0x00007FF9CC7A2651 (ntdll) RtlUserThreadStart

**Comment by brokenmass** [comment]
fixed in betterFPS 1.0.5 . thanks for the report !
