### ISSUE TITLE
[Bug][BetterFPS 1.05]Game crashes when research completes

### ISSUE THREAD

**Issue by Alneys** [DysonSphereMod/QOL#93]
I have seen some closed issues about this, but I still encountered this issue when I start a new save.

It seems to work well in my old save when an universe matrix researsh completes.

========== OUTPUTTING STACK TRACE ==================

0x00007FFB07740F40 (UnityPlayer) UnityMain
0x00007FFB07741FFF (UnityPlayer) UnityMain
0x00007FFB0773760E (UnityPlayer) UnityMain
0x00007FFB077341E3 (UnityPlayer) UnityMain
0x00007FFB0775389B (UnityPlayer) UnityMain
0x0000028984018871 (Mono JIT Code) (wrapper managed-to-native) UnityEngine.TextGenerator:Populate_Internal_Injected (string,UnityEngine.Font,UnityEngine.Color&,int,single,single,UnityEngine.FontStyle,bool,bool,int,int,int,int,bool,UnityEngine.TextAnchor,single,single,single,single,bool,bool,uint&)
0x00000289840186A8 (Mono JIT Code) UnityEngine.TextGenerator:Populate_Internal (string,UnityEngine.Font,UnityEngine.Color,int,single,single,UnityEngine.FontStyle,bool,bool,int,int,int,int,bool,UnityEngine.TextAnchor,single,single,single,single,bool,bool,uint&)
0x0000028984018528 (Mono JIT Code) UnityEngine.TextGenerator:Populate_Internal (string,UnityEngine.Font,UnityEngine.Color,int,single,single,UnityEngine.FontStyle,bool,bool,int,int,UnityEngine.VerticalWrapMode,UnityEngine.HorizontalWrapMode,bool,UnityEngine.TextAnchor,UnityEngine.Vector2,UnityEngine.Vector2,bool,bool,UnityEngine.TextGenerationError&)
0x0000028984018067 (Mono JIT Code) UnityEngine.TextGenerator:PopulateAlways (string,UnityEngine.TextGenerationSettings)
0x0000028984017DBE (Mono JIT Code) UnityEngine.TextGenerator:PopulateWithError (string,UnityEngine.TextGenerationSettings)
0x0000028A81E71A64 (Mono JIT Code) UnityEngine.TextGenerator:Populate (string,UnityEngine.TextGenerationSettings)
0x0000028A81E875BB (Mono JIT Code) UnityEngine.TextGenerator:GetPreferredWidth (string,UnityEngine.TextGenerationSettings)
0x0000028A81E87476 (Mono JIT Code) UnityEngine.UI.Text:get_preferredWidth ()
0x0000028A81F0574B (Mono JIT Code) UIItemupNode:SetData (int,int,int,int)
0x0000028A81F04D48 (Mono JIT Code) UIItemup:Up (int,int)
0x0000028A81F066E8 (Mono JIT Code) GameHistoryData:GainTechAwards (int,int)
0x0000028982101D34 (Mono JIT Code) (wrapper dynamic-method) com.brokenmass.plugin.DSP.BetterFPS.BetterFPS:DMD<com.brokenmass.plugin.DSP.BetterFPS.BetterFPS::TechRelatedGameTick> (FactorySystem)
0x00000289E3F5C9FA (Mono JIT Code) com.brokenmass.plugin.DSP.BetterFPS.BetterFPS/<>c:<FactorySystem_DrawModels_Patch>b__8_1 (FactorySystem)
0x0000028984AE0E5A (Mono JIT Code) (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:<FactorySystem_DrawModels_Patch>b__8_1 (FactorySystem)
0x00000289821091DB (Mono JIT Code) (wrapper dynamic-method) FactorySystem:DMD<FactorySystem::GameTick> (FactorySystem,long,bool)
0x00000289E3F4F6F6 (Mono JIT Code) PlanetFactory:GameTick (long)
0x00000289E3F4B53C (Mono JIT Code) com.brokenmass.plugin.DSP.BetterFPS.BetterFPS/<>c__DisplayClass6_1:<GameData_GameTick_Patch>b__1 ()
0x00000289E3F4ACFB (Mono JIT Code) System.Threading.Tasks.Task:InnerInvoke ()
0x00000289E3F49C0C (Mono JIT Code) System.Threading.Tasks.Task:Execute ()
0x00000289E3F48DFB (Mono JIT Code) System.Threading.Tasks.Task:ExecutionContextCallback (object)
0x00000289E3F43922 (Mono JIT Code) System.Security.SecurityContext:Run (System.Security.SecurityContext,System.Threading.ContextCallback,object)
0x00000289E3F42416 (Mono JIT Code) System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
0x00000289E3F41C2F (Mono JIT Code) System.Threading.Tasks.Task:ExecuteWithThreadLocal (System.Threading.Tasks.Task&)
0x00000289E3F411F9 (Mono JIT Code) System.Threading.Tasks.Task:ExecuteEntry (bool)
0x00000289E3F41018 (Mono JIT Code) System.Threading.Tasks.ThreadPoolTaskScheduler:TaskExecuteWaitCallback (object)
0x00000289D2EF0136 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this___object (object,intptr,intptr,intptr)
0x00007FFB0A266783 (mono) mono_set_defaults
0x00007FFB0A1B8AD9 (mono) mono_runtime_invoke
0x00007FFB0A1BEFEF (mono) mono_runtime_invoke_array
0x00007FFB0A1BF2C4 (mono) mono_runtime_invoke_array
0x00007FFB0A1DF95B (mono) mono_security_set_mode
0x00007FFB0A1E03B2 (mono) mono_security_set_mode
0x00007FFB0A1E40FF (mono) mono_thread_interruption_request_flag
0x00007FFB0A29A1AB (mono) mono_unity_gc_is_disabled
0x00007FFB7E717C24 (KERNEL32) BaseThreadInitThunk
0x00007FFB8044D4D1 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

**Comment by Alneys** [comment]
For reference, this is my factory. The game crashes when research _Fluid Storage Encapsulation_ is complete, the next research is _High-Efficiency Plasma Control_.

![20210427024809_1](https://user-images.githubusercontent.com/35741726/116200397-4a1d2b00-a706-11eb-964d-87c2fc868dee.jpg)

**Comment by brokenmass** [comment]
@Alneys thank you for the report, i will fix it in the next version.

**Comment by brokenmass** [comment]
BetterFPS is now deprecated
